### PR TITLE
Update ClickGui.java

### PR DESCRIPTION
**Pull request by gyu29**
cleaned up messy code
(pls write better) :)

### CODE REVIEW

**Comment by gyu29** [comment]
took me forever

**Comment by Tryflle** [comment]
can you please like
merge these prs into one pr...

**Comment by gyu29** [comment]
ok

**Comment by gyu29** [comment]
wait uh

**Comment by gyu29** [comment]
i realized idk how to merge prs

**Comment by Tryflle** [comment]
Close your existing prs and make a new one. It will contain all of the commits you have made.

**Comment by Tryflle** [comment]
closing until you merge these into one because there are 7 of them and you still havent merged them into one

**Pull request closed without merging**
