### PR TITLE
Updated Theme.java

### PR DESCRIPTION
**Pull request by gyu29**
Made it so that there is an option for custom theme
haven't tested so idk if it works

### CODE REVIEW

**Comment by Tryflle** [comment]
You should always test things you add- especially if you are PRing.
I will test it tmrw.

**Comment by gyu29** [comment]
kk

**Comment by gyu29** [comment]
i was just too lazy

**Comment by gyu29** [comment]
to compile it

**Comment by Tryflle** [comment]
closing until you merge these into one because there are 7 of them and you still havent merged them into one

**Pull request closed without merging**
